
server:
  servlet:
    context-path: /ministore-auth-api
  port: 8083

spring:
  application:
    name: ministore-auth-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:auth
    username: root
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
security:
  jwt:
    token:
      secret-key: 3a8382882b7bdf58b7d3abcb3f6aa867
      expire-length: 360000
# PATHS
# http://localhost:8083/ministore-auth-api/h2-console/
